"""
Django settings for seamap project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-d%xr13cxhs+hl0czf5^(g6fo-dt-p$!&ti1j5d(8g=sd&nf0-1')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# Get Railway URLs
RAILWAY_STATIC_URL = os.getenv('RAILWAY_STATIC_URL')
RAILWAY_PUBLIC_DOMAIN = os.getenv('RAILWAY_PUBLIC_DOMAIN')

# Configure ALLOWED_HOSTS
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Add Railway domains
if RAILWAY_STATIC_URL:
    domain = RAILWAY_STATIC_URL.replace('https://', '').replace('http://', '')
    ALLOWED_HOSTS.append(domain)

if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)

# Add common Railway patterns
ALLOWED_HOSTS.extend([
    'sea-map-staging.up.railway.app',  # Your current deployment
    '.railway.app',  # Allows any subdomain of railway.app
    '.up.railway.app'  # Allows any subdomain of up.railway.app
])

# CSRF trusted origins for Railway
CSRF_TRUSTED_ORIGINS = [
    'https://sea-map-staging.up.railway.app'
]

if RAILWAY_STATIC_URL:
    # Ensure the URL has a scheme
    if not RAILWAY_STATIC_URL.startswith(('http://', 'https://')):
        RAILWAY_STATIC_URL = 'https://' + RAILWAY_STATIC_URL
    CSRF_TRUSTED_ORIGINS.append(RAILWAY_STATIC_URL)

if RAILWAY_PUBLIC_DOMAIN:
    # Ensure the domain has a scheme
    domain_url = RAILWAY_PUBLIC_DOMAIN
    if not domain_url.startswith(('http://', 'https://')):
        domain_url = 'https://' + domain_url
    CSRF_TRUSTED_ORIGINS.append(domain_url)

# For development
if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend([
        'http://localhost:8000',
        'http://127.0.0.1:8000'
    ])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'member',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For serving static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'member.backends.EmailBackend',  # Custom email authentication
    'django.contrib.auth.backends.ModelBackend',  # Default username authentication
]

# Login/Logout URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

ROOT_URLCONF = 'seamap.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'seamap.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Use Railway's DATABASE_URL if available, otherwise PostgreSQL for local development
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Production database (Railway or other hosting)
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, conn_health_checks=True)
    }
else:
    # Local development database (PostgreSQL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'seamap_db'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Production static files settings
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise settings for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Security settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os
# File upload settings
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Cloudflare R2 Storage Settings
# Automatically enable R2 for Railway, disable for local development
IS_RAILWAY = 'RAILWAY_ENVIRONMENT' in os.environ
USE_CLOUDFLARE_R2 = IS_RAILWAY and os.getenv('USE_CLOUDFLARE_R2', 'True').lower() == 'true'

if USE_CLOUDFLARE_R2:
    # Cloudflare R2 Configuration for Railway production
    CLOUDFLARE_R2_ACCESS_KEY_ID = os.getenv('CLOUDFLARE_R2_ACCESS_KEY_ID')
    CLOUDFLARE_R2_SECRET_ACCESS_KEY = os.getenv('CLOUDFLARE_R2_SECRET_ACCESS_KEY')
    CLOUDFLARE_R2_BUCKET_NAME = os.getenv('CLOUDFLARE_R2_BUCKET_NAME')
    CLOUDFLARE_R2_ENDPOINT_URL = os.getenv('CLOUDFLARE_R2_ENDPOINT_URL')
    CLOUDFLARE_R2_CUSTOM_DOMAIN = os.getenv('CLOUDFLARE_R2_CUSTOM_DOMAIN')
    
    # Use custom storage backends
    DEFAULT_FILE_STORAGE = 'seamap.storage_backends.PublicMediaStorage'
    
    # Add storages app to INSTALLED_APPS for R2
    INSTALLED_APPS.append('storages')
    
    # Media URL will use custom domain if available
    if CLOUDFLARE_R2_CUSTOM_DOMAIN:
        MEDIA_URL = f'https://{CLOUDFLARE_R2_CUSTOM_DOMAIN}/media/'
    else:
        MEDIA_URL = f'{CLOUDFLARE_R2_ENDPOINT_URL}/{CLOUDFLARE_R2_BUCKET_NAME}/media/'
else:
    # Local development settings - use filesystem storage
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Railway specific settings
if IS_RAILWAY:
    # On Railway, create media directory if it doesn't exist (for fallback)
    os.makedirs(MEDIA_ROOT, exist_ok=True)

# Maximum file upload size (25MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024

# Allowed file extensions
ALLOWED_UPLOAD_EXTENSIONS = [
    '.pdf', '.doc', '.docx', '.ppt', '.pptx', '.jpg', '.jpeg', '.png', '.gif'
]
