# Generated by Django 4.2.8 on 2025-07-20 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('startup', 'Startup'), ('investor', 'Investor'), ('corporate', 'Corporate')], max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('team_size', models.CharField(blank=True, choices=[('1', '1 person (Solo founder)'), ('2-5', '2-5 people'), ('6-10', '6-10 people'), ('11-25', '11-25 people'), ('26-50', '26-50 people'), ('51-100', '51-100 people'), ('100+', '100+ people')], max_length=10)),
                ('primary_location', models.CharField(blank=True, choices=[('Singapore', '🇸🇬 Singapore'), ('Indonesia', '🇮🇩 Indonesia'), ('Thailand', '🇹🇭 Thailand'), ('Malaysia', '🇲🇾 Malaysia'), ('Philippines', '🇵🇭 Philippines'), ('Vietnam', '🇻🇳 Vietnam'), ('Cambodia', '🇰🇭 Cambodia'), ('Laos', '🇱🇦 Laos'), ('Myanmar', '🇲🇲 Myanmar'), ('Brunei', '🇧🇳 Brunei'), ('Other', '🌍 Other')], max_length=50)),
                ('company_description', models.TextField(blank=True)),
                ('innovation_types', models.JSONField(blank=True, default=list)),
                ('solution_description', models.TextField(blank=True)),
                ('current_stage', models.CharField(blank=True, choices=[('idea', '💡 Ideation – Developing an idea, no product yet'), ('prototype', '🔧 Prototype – Initial MVP or prototype created'), ('validation', '🧪 Validation – Testing with early customers'), ('early', '📈 Early Growth – Generating revenue'), ('scaling', '🚀 Scaling – Expanding with proven model'), ('profitable', '💰 Established – Profitable and exploring new markets')], max_length=20)),
                ('funding_needed', models.CharField(blank=True, choices=[('under_10k', 'Under $10K'), ('10k_50k', '$10K - $50K'), ('50k_100k', '$50K - $100K'), ('100k_500k', '$100K - $500K'), ('500k_1m', '$500K - $1M'), ('1m_5m', '$1M - $5M'), ('5m_10m', '$5M - $10M'), ('over_10m', 'Over $10M'), ('not_seeking', 'Not currently seeking funding')], max_length=20)),
                ('support_areas', models.JSONField(blank=True, default=list)),
                ('support_details', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('consent_info', models.BooleanField(default=False)),
                ('consent_marketplace', models.BooleanField(default=False)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='member.member')),
            ],
        ),
    ]
