# Generated by Django 4.2.23 on 2025-07-20 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_job_position_member_linkedin_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('team_size', models.CharField(blank=True, choices=[('1', '1 person (Solo founder)'), ('2-5', '2-5 people'), ('6-10', '6-10 people'), ('11-25', '11-25 people'), ('26-50', '26-50 people'), ('51-100', '51-100 people'), ('100+', '100+ people')], max_length=10)),
                ('primary_location', models.CharField(blank=True, choices=[('Singapore', '🇸🇬 Singapore'), ('Indonesia', '🇮🇩 Indonesia'), ('Thailand', '🇹🇭 Thailand'), ('Malaysia', '🇲🇾 Malaysia'), ('Philippines', '🇵🇭 Philippines'), ('Vietnam', '🇻🇳 Vietnam'), ('Cambodia', '🇰🇭 Cambodia'), ('Laos', '🇱🇦 Laos'), ('Myanmar', '🇲🇲 Myanmar'), ('Brunei', '🇧🇳 Brunei'), ('Other', '🌍 Other')], max_length=50)),
                ('company_description', models.TextField(blank=True)),
                ('innovation_types', models.JSONField(blank=True, default=list)),
                ('solution_description', models.TextField(blank=True)),
                ('current_stage', models.CharField(blank=True, choices=[('idea', '💡 Ideation – Developing an idea, no product yet'), ('prototype', '🔧 Prototype – Initial MVP or prototype created'), ('validation', '🧪 Validation – Testing with early customers'), ('early', '📈 Early Growth – Generating revenue'), ('scaling', '🚀 Scaling – Expanding with proven model'), ('profitable', '💰 Established – Profitable and exploring new markets')], max_length=20)),
                ('funding_needed', models.CharField(blank=True, choices=[('under_10k', 'Under $10K'), ('10k_50k', '$10K - $50K'), ('50k_100k', '$50K - $100K'), ('100k_500k', '$100K - $500K'), ('500k_1m', '$500K - $1M'), ('1m_5m', '$1M - $5M'), ('5m_10m', '$5M - $10M'), ('over_10m', 'Over $10M'), ('not_seeking', 'Not currently seeking funding')], max_length=20)),
                ('support_areas', models.JSONField(blank=True, default=list)),
                ('support_details', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
            },
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member Profile', 'verbose_name_plural': 'Member Profiles'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='member',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='member',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='member',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='current_stage',
        ),
        migrations.RemoveField(
            model_name='member',
            name='founded_year',
        ),
        migrations.RemoveField(
            model_name='member',
            name='funding_needed',
        ),
        migrations.RemoveField(
            model_name='member',
            name='innovation_types',
        ),
        migrations.RemoveField(
            model_name='member',
            name='primary_location',
        ),
        migrations.RemoveField(
            model_name='member',
            name='solution_description',
        ),
        migrations.RemoveField(
            model_name='member',
            name='support_areas',
        ),
        migrations.RemoveField(
            model_name='member',
            name='support_details',
        ),
        migrations.RemoveField(
            model_name='member',
            name='team_size',
        ),
        migrations.RemoveField(
            model_name='member',
            name='website',
        ),
        migrations.AddField(
            model_name='member',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='company_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='member.company')),
            ],
            options={
                'verbose_name': 'Company Document',
                'verbose_name_plural': 'Company Documents',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='member.member'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('member', 'company_name')},
        ),
    ]
