# Generated by Django 4.2.23 on 2025-07-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_company_alter_member_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='average_deal_size',
            field=models.CharField(blank=True, choices=[('under_100k', 'Under $100K'), ('100k_500k', '$100K - $500K'), ('500k_1m', '$500K - $1M'), ('1m_5m', '$1M - $5M'), ('5m_10m', '$5M - $10M'), ('10m_50m', '$10M - $50M'), ('over_50m', 'Over $50M')], max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='funding_size',
            field=models.CharField(blank=True, choices=[('under_1m', 'Under $1M'), ('1m_50m', '$1M - $50M'), ('100m_200m', '$100M - $200M'), ('200m_500m', '$200M - $500M'), ('over_500m', 'Over $500M')], max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='funding_stages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='investment_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='investment_philosophy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='investor_type',
            field=models.CharField(blank=True, choices=[('angel', '🦸 Angel Investor'), ('vc', '💼 Venture Capital (VC)'), ('corporate', '🏢 Corporate Investor'), ('family_office', '👨\u200d👩\u200d👧\u200d👦 Family Office'), ('impact_fund', '🌱 Impact Fund'), ('government', '🏛️ Government/Development Agency'), ('other', '🔎 Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='market_country_interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
