# Generated by Django 4.2.23 on 2025-07-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_company_average_deal_size_company_funding_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('private_company', 'Private Company'), ('multinational_corporation', 'Multinational Corporation'), ('sme', 'Small or Medium-sized Enterprise (SME)'), ('startup_subsidiary', 'Startup Subsidiary'), ('other', 'Other')], max_length=30),
        ),
    ]
