# Generated by Django 4.2.23 on 2025-07-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_company_organization_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('startup', 'Startup'), ('investor', 'Investor'), ('corporate', 'Corporate')], default='startup', max_length=20),
        ),
    ]
