# Generated by Django 4.2.23 on 2025-07-21 05:03

from django.db import migrations

def transfer_user_type_to_company_type(apps, schema_editor):
    """Transfer user_type from Member to company_type in Company"""
    Member = apps.get_model('member', 'Member')
    Company = apps.get_model('member', 'Company')
    
    # Update each company's company_type based on its member's user_type
    for company in Company.objects.all():
        if company.member and company.member.user_type:
            company.company_type = company.member.user_type
            company.save()
    
def reverse_transfer(apps, schema_editor):
    """Reverse operation - transfer company_type back to Member user_type"""
    Member = apps.get_model('member', 'Member')
    Company = apps.get_model('member', 'Company')
    
    # For reverse, we'd need to decide which company type to use if a member has multiple companies
    # For now, just use the first company's type
    for member in Member.objects.all():
        first_company = member.companies.first()
        if first_company and first_company.company_type:
            member.user_type = first_company.company_type
            member.save()

class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_company_company_type'),
    ]

    operations = [
        migrations.RunPython(transfer_user_type_to_company_type, reverse_transfer),
    ]
