# Generated by Django 4.2.23 on 2025-07-21 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20250721_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user_type',
        ),
    ]
