# Generated by Django 4.2.23 on 2025-07-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_remove_member_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('startup', 'Startup'), ('investor', 'Investor'), ('corporate', 'Corporate')], max_length=20),
        ),
    ]
