# Generated by Django 4.2.23 on 2025-08-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_alter_company_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active_users_count',
            field=models.CharField(blank=True, help_text='Number of active users', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='amount_raised',
            field=models.CharField(blank=True, help_text='Amount raised in USD', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='annual_recurring_revenue',
            field=models.CharField(blank=True, help_text='Annual recurring revenue in USD', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='core_expertise',
            field=models.TextField(blank=True, help_text='Core expertise description'),
        ),
        migrations.AddField(
            model_name='company',
            name='core_team_size',
            field=models.CharField(blank=True, help_text='Core team size including founders', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='customer_segments',
            field=models.JSONField(blank=True, default=list, help_text='Customer segments'),
        ),
        migrations.AddField(
            model_name='company',
            name='financial_projections',
            field=models.TextField(blank=True, help_text='Financial projections'),
        ),
        migrations.AddField(
            model_name='company',
            name='funding_history',
            field=models.TextField(blank=True, help_text='Funding history details'),
        ),
        migrations.AddField(
            model_name='company',
            name='has_external_funding',
            field=models.BooleanField(default=False, help_text='Has secured external funding'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_female_led',
            field=models.BooleanField(default=False, help_text='Led or co-led by female founder'),
        ),
        migrations.AddField(
            model_name='company',
            name='paying_customers_count',
            field=models.CharField(blank=True, help_text='Number of paying customers', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='problem_statement',
            field=models.TextField(blank=True, help_text='Problem statement for startup'),
        ),
        migrations.AddField(
            model_name='company',
            name='target_markets',
            field=models.TextField(blank=True, help_text='Target markets description'),
        ),
        migrations.AddField(
            model_name='company',
            name='team_overview',
            field=models.TextField(blank=True, help_text='Team overview description'),
        ),
        migrations.AddField(
            model_name='company',
            name='use_of_funds',
            field=models.TextField(blank=True, help_text='Use of funds description'),
        ),
    ]
