# Generated by Django 4.2.23 on 2025-08-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_company_active_users_count_company_amount_raised_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry_expertise',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
