# Generated by Django 4.2.23 on 2025-08-04 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_company_industry_expertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(help_text='Main challenge description and overview')),
                ('organizer_contact', models.EmailField(max_length=254)),
                ('requirements_content', models.TextField(help_text='Rich text content for requirements and criteria')),
                ('categories', models.JSONField(blank=True, default=list, help_text='Challenge category tags')),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('has_prizes', models.BooleanField(default=False)),
                ('main_prize_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('main_prize_currency', models.CharField(default='USD', max_length=3)),
                ('prizes_content', models.TextField(blank=True, help_text='Rich text content for prizes and rewards')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('scope', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='challenges/')),
                ('applicant_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to='member.member')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='member.company')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(help_text='Main problem statement description')),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('current_challenges', models.TextField(help_text='Current challenges and pain points')),
                ('impact_categories', models.JSONField(blank=True, default=list, help_text='Impact category tags')),
                ('solution_requirements', models.TextField(help_text="Rich text content for what they're looking for")),
                ('technical_requirements', models.TextField(help_text='Rich text content for technical specifications')),
                ('collaboration_type', models.CharField(blank=True, max_length=100)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('implementation_support', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('industry_focus', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='problems/')),
                ('solution_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_statements', to='member.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_problems', to='member.member')),
            ],
            options={
                'verbose_name': 'Problem Statement',
                'verbose_name_plural': 'Problem Statements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='problem_documents/')),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='member.problemstatement')),
            ],
            options={
                'verbose_name': 'Problem Document',
                'verbose_name_plural': 'Problem Documents',
            },
        ),
        migrations.CreateModel(
            name='ChallengeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='challenge_documents/')),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='member.challenge')),
            ],
            options={
                'verbose_name': 'Challenge Document',
                'verbose_name_plural': 'Challenge Documents',
            },
        ),
    ]
