# Generated by Django 4.2.23 on 2025-08-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_challenge_problemstatement_problemdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_brief',
            field=models.FileField(blank=True, help_text='Challenge brief document', null=True, upload_to='challenge_briefs/'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='innovation_category',
            field=models.CharField(blank=True, choices=[('', 'Select category'), ('Innovation', 'Innovation'), ('Technology', 'Technology'), ('Sustainability', 'Sustainability'), ('Social Impact', 'Social Impact'), ('Digital Transformation', 'Digital Transformation'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Finance', 'Finance'), ('Environment', 'Environment'), ('Agriculture', 'Agriculture')], help_text='Innovation category for the challenge', max_length=100),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='problemstatement',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
