# Generated by Django 4.2.23 on 2025-08-05 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_challenge_challenge_brief_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='start_date',
        ),
    ]
