# Generated by Django 4.2.23 on 2025-08-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_remove_unused_challenge_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemstatement',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='problemstatement',
            name='industry_focus',
        ),
        migrations.RemoveField(
            model_name='problemstatement',
            name='priority',
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='support_offered',
            field=models.JSONField(blank=True, default=list, help_text='Types of support offered to solution providers'),
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='technical_specifications',
            field=models.FileField(blank=True, help_text='Technical specifications document', null=True, upload_to='problem_specifications/'),
        ),
        migrations.AlterField(
            model_name='problemstatement',
            name='technical_requirements',
            field=models.TextField(blank=True, help_text='Rich text content for technical specifications'),
        ),
    ]
