# Generated by Django 4.2.23 on 2025-08-08 08:54

from django.db import migrations, models
import member.upload_handlers


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_remove_problemstatement_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='average_deal_size',
            field=models.CharField(blank=True, choices=[('under_50k', 'Under $50K'), ('50k_250k', '$50K - $250K'), ('250k_1m', '$250K - $1M'), ('1m_5m', '$1M - $5M'), ('5m_25m', '$5M - $25M'), ('over_25m', 'Over $25M')], max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=member.upload_handlers.company_logo_upload_to),
        ),
        migrations.AlterField(
            model_name='company',
            name='funding_size',
            field=models.CharField(blank=True, choices=[('under_1m', 'Under $1M'), ('1m_50m', '$1M - $50M'), ('50m_250m', '$50M - $250M'), ('250m_1b', '$250M - $1B'), ('over_1b', 'Over $1B'), ('undisclosed', 'Undisclosed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=member.upload_handlers.profile_picture_upload_to),
        ),
    ]
