# Generated by Django 4.2.23 on 2025-08-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_update_funding_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='reviewer_notes',
            field=models.TextField(blank=True, help_text='Notes from reviewer'),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='average_deal_size',
            field=models.CharField(blank=True, choices=[('under_100k', 'Under $100K'), ('100k_500k', '$100K - $500K'), ('500k_1m', '$500K - $1M'), ('1m_5m', '$1M - $5M'), ('5m_10m', '$5M - $10M'), ('10m_50m', '$10M - $50M'), ('over_50m', 'Over $50M')], max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='funding_size',
            field=models.CharField(blank=True, choices=[('under_1m', 'Under $1M'), ('1m_50m', '$1M - $50M'), ('100m_200m', '$100M - $200M'), ('200m_500m', '$200M - $500M'), ('over_500m', 'Over $500M')], max_length=20),
        ),
    ]
