# Generated by Django 4.2.23 on 2025-09-05 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0018_memberdocument_reviewed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdocument',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='memberdocument',
            name='reviewer_notes',
        ),
        migrations.RemoveField(
            model_name='memberdocument',
            name='status',
        ),
        migrations.AddField(
            model_name='company',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes about verification'),
        ),
        migrations.AddField(
            model_name='company',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', help_text='Company verification status by admin', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the company was verified', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who verified this company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes about verification'),
        ),
        migrations.AddField(
            model_name='member',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', help_text='Profile verification status by admin', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the profile was verified', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who verified this profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
