# Generated by Django 4.2.23 on 2025-09-05 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0019_add_verification_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Company Document', 'verbose_name_plural': 'Company Documents'},
        ),
        migrations.AlterModelOptions(
            name='memberdocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Member Document', 'verbose_name_plural': 'Member Documents'},
        ),
        migrations.AddField(
            model_name='companydocument',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companydocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_company_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companydocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='document_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_member_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20),
        ),
    ]
