# Generated by Django 4.2.23 on 2025-09-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0020_add_document_verification_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemstatement',
            name='support_offered',
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='innovation_type',
            field=models.JSONField(blank=True, default=list, help_text='Types of innovation sought'),
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='preferred_asean_countries',
            field=models.JSONField(blank=True, default=list, help_text='Preferred ASEAN countries for solutions'),
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='startup_stage',
            field=models.JSONField(blank=True, default=list, help_text='Preferred startup maturity levels'),
        ),
        migrations.AlterField(
            model_name='company',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('private_company', '🏢 Private Company'), ('multinational_corporation', '🌐 Multinational Corporation'), ('sme', '🏭 Small or Medium-sized Enterprise (SME)'), ('startup_subsidiary', '🚀 Startup Subsidiary'), ('other', 'Other')], max_length=30),
        ),
    ]
