# Generated by Django 4.2.23 on 2025-09-15 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0021_remove_problemstatement_support_offered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemstatement',
            name='impact_categories',
        ),
    ]
