# Generated by Django 4.2.23 on 2025-09-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0022_remove_problemstatement_impact_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemstatement',
            name='budget_range',
        ),
        migrations.RemoveField(
            model_name='problemstatement',
            name='collaboration_type',
        ),
        migrations.RemoveField(
            model_name='problemstatement',
            name='region',
        ),
    ]
