# Generated by Django 4.2.23 on 2025-09-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0023_remove_problemstatement_budget_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocument',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the document'),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the document'),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='document_type',
            field=models.CharField(choices=[('pitch_deck', 'Pitch Deck'), ('business_plan', 'Business Plan'), ('financial_statements', 'Financial Statements'), ('company_registration', 'Company Registration'), ('technical_docs', 'Technical Documentation'), ('market_research', 'Market Research'), ('product_demo', 'Product Demo'), ('legal_docs', 'Legal Documents'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='document_type',
            field=models.CharField(choices=[('id_card', 'ID Card'), ('passport', 'Passport'), ('cv', 'CV/Resume'), ('certificate', 'Certificate'), ('portfolio', 'Portfolio'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
