# Generated by Django 4.2.23 on 2026-01-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0025_member_two_factor_enabled_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocument',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Make this document visible on company profile'),
        ),
        migrations.AlterField(
            model_name='company',
            name='primary_location',
            field=models.CharField(blank=True, choices=[('Singapore', '🇸🇬 Singapore'), ('Indonesia', '🇮🇩 Indonesia'), ('Thailand', '🇹🇭 Thailand'), ('Malaysia', '🇲🇾 Malaysia'), ('Philippines', '🇵🇭 Philippines'), ('Vietnam', '🇻🇳 Vietnam'), ('Cambodia', '🇰🇭 Cambodia'), ('Laos', '🇱🇦 Laos'), ('Myanmar', '🇲🇲 Myanmar'), ('Brunei', '🇧🇳 Brunei'), ('Timor Leste', '🇹🇱 Timor Leste'), ('Other', '🌍 Other')], max_length=50),
        ),
    ]
